/*
 * St. Louis Places API
 *
 * An API for discovering places of interest in St. Louis, Missouri.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse200 struct {

	Places []InlineResponse200Places `json:"places,omitempty"`
}
