/*
 * St. Louis Places API
 *
 * An API for discovering places of interest in St. Louis, Missouri.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse200Places struct {

	Name string `json:"name,omitempty"`

	Address string `json:"address,omitempty"`

	Rating float64 `json:"rating,omitempty"`

	Photos []string `json:"photos,omitempty"`
}
